# Generated by Django 3.2 on 2023-01-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='deafult_emergency_contact',
            new_name='default_emergency_contact',
        ),
    ]
