# Generated by Django 3.2 on 2023-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_deafult_emergency_contact_userprofile_default_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_emergency_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
