# Generated by Django 3.2 on 2023-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, unique=True, verbose_name='Activity type')),
                ('published_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.IntegerField(verbose_name='Duration (days)')),
                ('distance', models.IntegerField(verbose_name='Distance (km)')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('date', models.DateField(verbose_name='Date')),
                ('difficulty', models.IntegerField(choices=[(0, 'Super easy'), (1, 'Easy'), (2, 'Moderate'), (3, 'Challenging'), (4, 'Very challenge'), (5, 'Extremely challenging')], default=3)),
                ('published_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
