# Generated by Django 3.2 on 2023-01-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230117_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.activity'),
        ),
    ]
