# Generated by Django 3.2 on 2023-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Super easy'), (1, 'Easy'), (2, 'Moderate'), (3, 'Challenging'), (4, 'Very challenging'), (5, 'Extremely challenging')], default=3),
        ),
    ]
