# Generated by Django 3.2 on 2023-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emergency_number',
            field=models.CharField(max_length=20),
        ),
    ]
