# Generated by Django 3.2 on 2023-01-28 18:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_emergency_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emergency_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
