# Generated by Django 3.2 on 2023-01-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_emergency_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emergency_number',
            field=models.CharField(max_length=20),
        ),
    ]
